development:
  s3_id: AKIAIAG4BLB5CUCNAWZQ
  s3_secret: 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
  s3_bucket: assets-dev.website.com
test:
  s3_id: AKIAIAG4BLB5CUCNAWZQ
  s3_secret: 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
  s3_bucket: assets-dev.website.com
production:
  s3_id: AKIAIAG4BLB5CUCNAWZQ
  s3_secret: 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
  s3_bucket: assets-dev.website.com