---
pid: /home/deployer/apps/eo/current/tmp/pids/faye.pid
address: 0.0.0.0
timeout: 120
port: 9292
log: /home/deployer/apps/eo/current/log/faye.log
max_conns: 2048
require: []
max_persistent_conns: 4048
environment: production
servers: 1
daemonize: true